name: CI

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.js'
      - '**/*.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.23 # Specify your Bun version here

      - run: bun install
      - run: bun run test # Adjust if necessary
